### ISSUE TITLE
[BUG/简体中文]: 在使用等级预览功能中，出现了等级预览皮肤不正确的情况

### ISSUE THREAD

**Issue by Vanilluv** [GamerNoTitle/Valora#130]
### 请选择你所使用的Valora版本

正式版 https://val.bili33.top

### 请输入你遇到问题的网址（例如：https://val.bili33.top/market）

https://val.bili33.top/market

### 请提供复现的步骤

在这里，我想要预览光谱斗牛的皮肤效果，点击光谱斗牛的等级预览，显示如下：
![image](https://github.com/GamerNoTitle/Valora/assets/47251157/4ca7ec5d-ebbe-4c53-a15b-e56bb76ee7ce)
点开等级预览，发现皮肤的视频也对不上，在这里是第四个皮肤，也就是龙狙：
![image](https://github.com/GamerNoTitle/Valora/assets/47251157/1fdc8b39-9e2f-404f-9b13-ed5d232eca5e)
明天再看看会不会出现这个问题

**Comment by Vanilluv** [comment]
顺带一提，当我预览RGBCZ，也就是第三个皮肤的时候，返回键也是在光谱斗牛后面，然后皮肤预览选项也还是在龙狙后面。

**Comment by Vanilluv** [comment]
jin今天只有两个可以预览的皮肤，当我预览异星小刀，返回键在鱼缸恶灵处，当我预览鱼缸恶灵，出现的是异星小刀预览
![image](https://github.com/GamerNoTitle/Valora/assets/47251157/20722c46-eab8-490a-9317-7120e944cab1)

**Comment by GamerNoTitle** [comment]
emmmm下次放假统一成手机端的卡片式好了，表格太难维护了，样式也不统一
