### ISSUE TITLE
[BUG/简体中文]: 

### ISSUE THREAD

**Issue by wiop93256** [GamerNoTitle/Valora#156]
### 请选择你所使用的Valora版本

正式版 https://val.bili33.top

### 请输入你遇到问题的网址（例如：https://val.bili33.top/market）

top

### 请提供复现的步骤

请教大佬，怎么解决CF报错Code:1015,或者RateLimit？
我在使用您的项目部署后，经常出现类似的情况，但是网友说他们的API支持3W+号的同时查询。
如果能指点一二，我将不胜感激！

### 请贴入报错页面弹出的日志

```shell
无
```

### 请提供相关信息的截图

无

**Comment by GamerNoTitle** [comment]
如果你是一开始就弹1015的话，换个IP吧，IP不干净
如果你是用了一段时间才1015，说明确实太频繁了，要么等着解开，要么就换代理IP

**Comment by wiop93256** [comment]
> 如果你是一开始就弹1015的话，换个IP吧，IP不干净 如果你是用了一段时间才1015，说明确实太频繁了，要么等着解开，要么就换代理IP

我是请求了3个左右的账号，就被提示1015了，请问大佬，如何做到3w+号异步查询？只能加代理IP来做吗？

**Comment by GamerNoTitle** [comment]
> > 如果你是一开始就弹1015的话，换个IP吧，IP不干净 如果你是用了一段时间才1015，说明确实太频繁了，要么等着解开，要么就换代理IP
> 
> 我是请求了3个左右的账号，就被提示1015了，请问大佬，如何做到3w+号异步查询？只能加代理IP来做吗？

是的 如果是大量的话一定要用代理服务器
梯子也好 动态IP代理也好 主要看哪个适合你的需求
3W+的话把线程也得拉起来 我这个项目是个人用的没有考虑给商用的

**Comment by wiop93256** [comment]
> > > 如果你是一开始就弹1015的话，换个IP吧，IP不干净 如果你是用了一段时间才1015，说明确实太频繁了，要么等着解开，要么就换代理IP
> > 
> > 
> > 我是请求了3个左右的账号，就被提示1015了，请问大佬，如何做到3w+号异步查询？只能加代理IP来做吗？
> 
> 是的 如果是大量的话一定要用代理服务器 梯子也好 动态IP代理也好 主要看哪个适合你的需求 3W+的话把线程也得拉起来 我这个项目是个人用的没有考虑给商用的

感谢大佬回复，我懂了！

**Comment by GamerNoTitle** [comment]
代理的话如果Python挂不上代理可以试试用Proxifier这个软件 加个Python的规则（如图）
![image](https://github.com/user-attachments/assets/29e1da6d-1c40-476e-b485-d0609c9c3e5d)

**Comment by wiop93256** [comment]
> 代理的话如果Python挂不上代理可以试试用Proxifier这个软件 加个Python的规则（如图） ![image](https://private-user-images.githubusercontent.com/28426291/348207708-29e1da6d-1c40-476e-b485-d0609c9c3e5d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3NzYyMzYsIm5iZiI6MTcyMDc3NTkzNiwicGF0aCI6Ii8yODQyNjI5MS8zNDgyMDc3MDgtMjllMWRhNmQtMWM0MC00NzZlLWI0ODUtZDA2MDljOWMzZTVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzEyVDA5MTg1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE2OTBhNTJhZDc3OTViN2U1NDRhNWI1MGI2YTUwOTBmNDJlMTFkNzU0YTQwNjExYTRhNzdhMTcwNGEwNGRjZWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.53QdXMrA9Yos15kxSoyB_6n9drrPg1BTW0aYbDUCKyE)

好的大佬 我研究一下
