### ISSUE TITLE
[BUG/简体中文]: 替换字段变量传参问题导致500

### ISSUE THREAD

**Issue by ddhy00** [GamerNoTitle/Valora#158]
### Please select the Valora version you are using

Official Version https://val.bili33.top

### If you selected "third-party version", please enter the Valora URL you are using here

https://val.bili33.top/market

### Please enter the URL where you encountered the issue (e.g., https://val.bili33.top/market)

https://val.bili33.top/market

### Please provide the steps to reproduce the issue

2种解决方式都尝试了 但还是不行

### Please paste the logs displayed on the error page

```shell
服务器发生了以下错误：
Traceback （the recent call last ）：
文件“/usr/local/lib/python3.10/site-packages/flask/app.py”，第 2529 行，在 wsgi_app
响应 = self.full_dispatch_request（）
文件“/usr/local/lib/python3.10/site-packages/flask/app.py”，第 1825 行，在 full_dispatch_request
rv = self.handle_user_exception（e）
文件“/usr/local/lib/python3.10/site-packages/flask/app.py”，第 1823 行，在 full_dispatch_request
rv = self.dispatch_request（）
文件“/usr/local/lib/python3.10/site-packages/flask/app.py”，第 1799 行，在 dispatch_request
返回 self.ensure_sync（self.view_functions[rule.endpoint]）（**view_args）
文件“/app/app.py”，第 170 行，在 market_handler
return market（app， request， g.lang）
文件“/app/utils/Register.py”，第 59 行，在市场
中weapon_target = weapon（weapon_item['OfferID']， weapon_item[“成本”][“85ad13f7-3d1b-5128-9eb2-7cd8ee0b5741”]， lang=str（lang））
文件“/app/utils/Weapon.py”，第 63 行，在 __init__
level['displayName'] = level['displayName'].replace（descr， ''）
TypeError： replace（） 参数 1 must be str， not list

你可以尝试【刷新网页】或者点击下方的“重置网站数据”按钮来解决这个问题。
如果你已经点击了下面的按钮，但仍然出现了这个问题，请尝试清除浏览器的cookie来重置会话
，如果上面这两种方法你都已经尝试过了，那么请带着此错误信息联系开发者！
```

**Comment by GamerNoTitle** [comment]
好像是我的问题，方便透露一下今天刷到的是什么皮肤嘛？

**Comment by ddhy00** [comment]
今天还不知道呢，刚刚准备查看 然后就发现进不去了 hh 就来找你反映了一下

**Comment by GamerNoTitle** [comment]
方便上号看一下嘛？我得搞清楚是哪个皮肤上出的问题

**Comment by ddhy00** [comment]
这个似乎跟皮肤没关 我刚刚登录了6-7个号都是这样

**Comment by GamerNoTitle** [comment]
@ddhy00 我看到啥问题了 正在修

**Comment by GamerNoTitle** [comment]
@GamerNoTitle 改代码的时候有一部分没改到 导致新的替换方法没有改上去

**Comment by ddhy00** [comment]
这里我想请教一个问题，这个有办法做一个能登录缓存几千或几万账号的网站，每天就不需要登录就可以直接查看这些账号的商店状态

**Comment by GamerNoTitle** [comment]
> 这里我想请教一个问题，这个有办法做一个能登录缓存几千或几万账号的网站，每天就不需要登录就可以直接查看这些账号的商店状态

淘宝初始号业务嘛
缓存账号状态不太行，但是如果你有账号密码没开二步验证就可以每天自己让它刷新全自动

**Comment by GamerNoTitle** [comment]
应该可以了 你试试

**Comment by GamerNoTitle** [comment]
@ddhy00 配置没啥要求 又不是什么游戏服务器
主要是你服务器的IP得干净 不然会被拳头BAN
就按照之前找过我的那些淘宝商家 大多数都是IP不干净导致的被BAN
如果被BAN了 我的建议是找代理IP商 就是成本可能会多那么一点

**Comment by ddhy00** [comment]
我直接在腾讯云这种，买一个海外的服务器 然后这个服务器就只做这一个网站功能 这样ip是不是就可以解决了

**Comment by GamerNoTitle** [comment]
@ddhy00 你那个海外服务器请求不要太频繁哦 会触发RATE LIMIT的（亲测

**Comment by ddhy00** [comment]
好的 感谢
