### ISSUE TITLE
[Advance]改进商店页面显示逻辑的问题

### ISSUE THREAD

**Issue by Vanilluv** [GamerNoTitle/Valora#65]
![image](https://github.com/GamerNoTitle/Valora/assets/47251157/704d7962-a632-43af-80a4-1301d1a898ac)
英文页面下，当武器皮肤名字过长时，需要拉动下方滑动条才能完整显示右侧内容

**Comment by GamerNoTitle** [comment]
![image](https://github.com/GamerNoTitle/Valora/assets/28426291/4e57ca23-4f7a-43c2-90b4-3e7e57a78168)
目前已经通过把表格改成最宽的方式来解决这个问题
